"""Add book index table

Revision ID: 285eda1f35f3
Revises: 3f975ddefbd9
Create Date: 2025-09-25 14:02:36.501165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '285eda1f35f3'
down_revision: Union[str, Sequence[str], None] = '3f975ddefbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('pages_json', sa.JSON(), nullable=False),
    sa.Column('ts_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', term)", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_book_index_ts_vector', 'book_index', ['ts_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_index_ts_vector', table_name='book_index', postgresql_using='gin')
    op.drop_table('book_index')
    # ### end Alembic commands ###
