"""Add bookmarks col to user table

Revision ID: 314e527774c9
Revises: 85c43c96af0c
Create Date: 2025-09-27 10:18:15.785196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '314e527774c9'
down_revision: Union[str, Sequence[str], None] = '85c43c96af0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
