"""Add new tables

Revision ID: 3f975ddefbd9
Revises: e410966275f8
Create Date: 2025-09-25 10:17:06.237812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f975ddefbd9'
down_revision: Union[str, Sequence[str], None] = 'e410966275f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('books', sa.Column('collection_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('books_chroma_collection_name_key'), 'books', type_='unique')
    op.create_unique_constraint(None, 'books', ['collection_name'])
    op.drop_column('books', 'chroma_collection_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('chroma_collection_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='unique')
    op.create_unique_constraint(op.f('books_chroma_collection_name_key'), 'books', ['chroma_collection_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('books', 'collection_name')
    op.drop_table('page_content')
    # ### end Alembic commands ###
