"""Refactor models to use SQLModel

Revision ID: 7df346b8b8ed
Revises: 285eda1f35f3
Create Date: 2025-09-26 10:19:16.861498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7df346b8b8ed'
down_revision: Union[str, Sequence[str], None] = '285eda1f35f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_index', 'term',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('book_index', 'pages_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('chat_histories', 'messages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('page_content', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page_content', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat_histories', 'messages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('book_index', 'pages_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('book_index', 'term',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
