"""Update chat history to include user id

Revision ID: d263c9b777bb
Revises: d05edba7b069
Create Date: 2025-09-29 11:16:21.577365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd263c9b777bb'
down_revision: Union[str, Sequence[str], None] = 'd05edba7b069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chat_histories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_histories', type_='foreignkey')
    op.drop_column('chat_histories', 'user_id')
    # ### end Alembic commands ###
